### ISSUE TITLE
Can't backup database, error in source files.

### ISSUE THREAD

**Issue by CluelessCoffee** [amoracr/yii2-backup#4]
Error: Entry "public_html" of amoracr\backup\Backup::directories" can not be empty"

Backup component, line 277:
`is_string($directory) && empty($this->$directory)`
Should be:
`is_string($directory) && empty($directory)`

$this->directory is not a member of the Backup component.

Thanks

**Comment by amoracr** [comment]
Hi  @CluelessCoffee Thank you for reporting this. I will fix this asap.

**Comment by amoracr** [comment]
Hi @CluelessCoffee I fixed the issue and released a new version with it.  Let me know if this fix works, so I can close the issue.
Fixed in 1.3.3
